【功能模块开发】任务调度/评测机池
ThinkSpiritLab/heng-controller pull request #14
Opened 2020-12-18 15:05 UTC by fitenne

Fixes #10 

评测机池
  添加 login、logout、getToken

评测队列
  修改 push 参数为 JudgeRequest

添加调度、评测队列文档

添加调试用接口 login、logout

2020-12-18 15:08 UTC, A0nameless0man commented on src/scheduler/judge-queue-service/judge-queue-service.service.ts
> +            return client.rpush(
这个return有意义吗……

2020-12-19 02:00 UTC, fitenne commented on src/scheduler/judge-queue-service/judge-queue-service.service.ts
> +            return client.rpush(
已删除。

2021-01-31 07:37 UTC, Flaryer requested changes

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/judge-queue-service/judge-queue-service.service.ts
> +    async push(judgeRequest: JudgeRequest): Promise<string> {
push进来的应该是taskid，而没有详细内容

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/judge-queue-service/judge-queue-service.service.ts
> +    async pop(): Promise<JudgeRequest> {
这里应该也是taskid

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/judge-queue-service/judge-queue-service.service.ts
> +        await this.redisService.withClient(async client => {
```ts
        await this.redisService.withClient(async client => 
            await client.lpush(
                JudgeQueueService.pendingQueue,
                JSON.stringify(judgeRequest)
            );
        );
// 或者
        await this.redisService.client.lpush(...)
```

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/judge-queue-service/judge-queue-service.service.ts
> +            client.rpush(
左push，右pop

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/judge-queue-service/judge-queue-service.service.ts
> +                await client.blpop(JudgeQueueService.pendingQueue, 0)
左push，右pop

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        for (let i = 0; i < capacity; ++i) {
```ts
let mu = this.redisService.client.multi();
for(...;...;...){
    mu=mu.sadd(...).lpush(...);
}
await mu.exec();

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +                this.redisService.client
await

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        await this.redisService.withClient(async client => {
```ts
        await this.redisService.withClient(async client => {
            return await client.blpop(JudgerPoolService.tokenCount, "0");
        });
or 
        await this.redisService.withClient(async client => 
            await client.blpop(JudgerPoolService.tokenCount, "0");
        );
```
左push，右pop

blpop第二个参数好像是timeout吧

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        )) as string;
判 undefined

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        for (let i = 0; ; ++i) {
若1235号令牌均已归还，4号未归还，则5号令牌不会被清理。

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +            this.redisService.client
期望上要检测评测机是否还在评测机池内，否则会归还失效令牌。

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/scheduler.debug.controller.ts
> +        return this.judgeQueue.push(createJudgeRequest.body.mainJudge);
await

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/scheduler.debug.controller.ts
> +        this.JudgerPool.logout(info["name"]);
await

2021-01-31 07:37 UTC, Flaryer commented on src/scheduler/scheduler.debug.controller.ts
> +        this.JudgerPool.login(info["name"], info["maxTaskCount"]);
await

2021-01-31 11:31 UTC, fitenne commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        for (let i = 0; i < capacity; ++i) {
已修改

2021-01-31 11:47 UTC, fitenne commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        )) as string;
```ts
        await this.redisService.withClient(async client => {
            return client.brpop(JudgerPoolService.tokenCount, 0);
        });
        const token = (await this.redisService.client.spop(
            JudgerPoolService.tokenBucket
        )) as string;
```
每个 token 对应 tokenCount 中一个元素。逻辑上此处不会得到 undefined。
得到 undefiend 要怎么处理？

2021-01-31 11:50 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        )) as string;
【如果】碰巧哪里出了bug，能拦住。

2021-01-31 12:02 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        )) as string;
其实应该是判null
```ts
if(!token) throw new Error("xxx");
```

2021-01-31 13:11 UTC, A0nameless0man requested changes
请将 @Flaryer 指出的部分修正，同时请记得修改文档。

2021-01-31 13:12 UTC, A0nameless0man commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        for (let i = 0; ; ++i) {
这里redis是否提供了通配符之类的东西？或者考虑上lua脚本？

2021-01-31 13:55 UTC, Nugine commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        for (let i = 0; ; ++i) {
不主动清理令牌，当获取令牌时丢弃无效的，这样如何？

2021-01-31 14:02 UTC, Nugine requested changes

2021-01-31 14:02 UTC, Nugine commented on src/scheduler/scheduler.debug.controller.ts
> +        @Body() createJudgeRequest: CreateJudgeRequest
应当使用 dto 验证 post 参数。参考 [类验证器](https://docs.nestjs.cn/7/pipes?id=%e7%b1%bb%e9%aa%8c%e8%af%81%e5%99%a8)。

2021-01-31 14:02 UTC, Nugine commented on src/scheduler/scheduler.debug.controller.ts
> +    async login(@Body() info: any): Promise<string> {
最好避免写出 any，这里应当使用 dto，如果仅用来测试，可以原地定义一下参数类型。例如 
```ts
info: { name: string, maxTaskCount: number }
```

2021-01-31 14:03 UTC, Nugine commented
主分支已更新，基于 master 分支 rebase 一下。

2021-02-01 06:24 UTC, A0nameless0man commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        for (let i = 0; ; ++i) {
也是一个方案

2021-02-01 06:31 UTC, A0nameless0man commented on src/scheduler/judger-pool/judger-pool.service.ts
> +    async login(judgerId: string, capacity: number): Promise<number> {
这里要不要同时传入Software信息？以后可能能修改算法支持特定语言评测机？

2021-02-01 06:51 UTC, fitenne commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        for (let i = 0; ; ++i) {
我喜欢 Nugine 的方法。
关于 “获取令牌时丢弃无效的”， @Flaryer 评测机状态在 Redis JudgerReport 中吗，我可以直接查询一下状态？
这样对评测机池来说，评测机注销就简化成了 “评测机交互” 部分直接改变一下评测机状态。

2021-02-01 06:54 UTC, fitenne commented on src/scheduler/judger-pool/judger-pool.service.ts
> +            this.redisService.client
[重定向](https://github.com/ThinkSpiritLab/heng-controller/pull/14#discussion_r567596065)

2021-02-01 07:03 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        for (let i = 0; ; ++i) {
同一评测机所有令牌的值一样可以吗（令牌放在队列里，可重复，失去了随机性），这样release的时候就不用携带token或者调用回调函数了（懒） @Nugine @A0nameless0man @fitenne

2021-02-01 07:05 UTC, Flaryer commented on src/scheduler/scheduler.service.ts
> +        while (true) {
循环内部需要加try catch，保证循环不会中断

2021-02-01 07:57 UTC, fitenne commented on src/scheduler/scheduler.debug.controller.ts
> +    async login(@Body() info: any): Promise<string> {
仅用来测试，使用了后者。

2021-02-01 08:31 UTC, fitenne commented on src/scheduler/scheduler.service.ts
> +        while (true) {
Re-request review

2021-02-01 12:09 UTC, Nugine approved these changes, later dismissed

2021-02-02 13:31 UTC, Nugine commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        for (let i = 0; ; ++i) {
> 同一评测机所有令牌的值一样可以吗（令牌放在队列里，可重复，失去了随机性），比如就是评测机id的值。另外令牌放队列里可以少维护一个tokenCount。这样release的时候就不用携带token或者调用回调函数了（懒） @Nugine @A0nameless0man @fitenne

我觉得没什么影响，可以这样简化。

2021-02-04 04:17 UTC, fitenne commented on src/scheduler/judger-pool/judger-pool.service.ts
> +    async login(judgerId: string, capacity: number): Promise<number> {
这个要怎么样？

2021-02-04 07:24 UTC, A0nameless0man approved these changes

2021-02-04 07:28 UTC, A0nameless0man commented on src/scheduler/scheduler.service.ts
> +                const [taskId, token] = await Promise.all([
解构赋值可以嵌套

```js
const [taskId, [token,releaser]] = await Promise.all...
```

2021-02-04 07:29 UTC, A0nameless0man commented on src/scheduler/scheduler.service.ts
> +                );
可以使用反引号拼接字符串

2021-02-04 07:31 UTC, A0nameless0man requested changes
请将 `console.out` 替换为 `Logger`

2021-02-04 07:33 UTC, A0nameless0man commented on src/scheduler/scheduler.service.ts
> +                const [taskId, token] = await Promise.all([
感觉这样写也不太美观……
@Nugine 大佬怎么看？

2021-02-04 07:37 UTC, fitenne commented on src/scheduler/scheduler.service.ts
> +                const [taskId, token] = await Promise.all([
修改了调度算法，现在不需要 `releaser` 了

2021-02-04 07:39 UTC, fitenne commented on src/scheduler/scheduler.service.ts
> +                );
这个是未写完的，不打算放到最后的代码里啊。

2021-02-04 07:46 UTC, A0nameless0man commented on src/scheduler/scheduler.service.ts
> +                );
了解了

2021-02-04 07:46 UTC, A0nameless0man approved these changes

2021-02-04 07:46 UTC, A0nameless0man approved these changes, later dismissed

2021-02-05 11:54 UTC, Flaryer commented on src/scheduler/judge-queue-service/judge-queue-service.service.ts
> +            return (await client.brpop(JudgeQueueService.pendingQueue, 0))[1];
阻塞监听的timeout不应该是0，这里可能要设置为10s，30s之类的，外面套一个while，判断是否成功取出了任务，没取出就重新监听。

2021-02-05 11:54 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +                return client.brpop(JudgerPoolService.tokenBucket, 0);
同上

2021-02-05 11:54 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +            if (ret === undefined) {
if(!ret)

2021-02-05 12:05 UTC, A0nameless0man commented on src/scheduler/judge-queue-service/judge-queue-service.service.ts
> +            return (await client.brpop(JudgeQueueService.pendingQueue, 0))[1];
我测试了一下，删除一个队列不能使其上的阻塞监听返回，甚至包括将其删除后将键值设为其它类型也不行。

2021-02-05 12:06 UTC, A0nameless0man approved these changes, later dismissed

2021-02-05 12:08 UTC, A0nameless0man commented on src/scheduler/judge-queue-service/judge-queue-service.service.ts
> +            return (await client.brpop(JudgeQueueService.pendingQueue, 0))[1];
不过只要这个队列没有惨遭删除的可能性，应该问题不大

2021-02-05 12:09 UTC, A0nameless0man commented on src/scheduler/judger-pool/judger-pool.service.ts
> +            if (ret === undefined) {
我其实更倾向于这种语义比较清晰的写法

2021-02-05 12:09 UTC, Flaryer commented on src/scheduler/judge-queue-service/judge-queue-service.service.ts
> +            return (await client.brpop(JudgeQueueService.pendingQueue, 0))[1];
😥好像一样的，目的都是一直监听，好像不改也行）

2021-02-05 12:10 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +            if (ret === undefined) {
好像不是undefined，而是null

2021-02-05 12:12 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +            if (ret === undefined) {
搞错了）确实是undefined😓

2021-02-05 12:14 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +            if (ret === undefined) {
null

2021-02-06 03:04 UTC, fitenne commented on src/scheduler/judge-queue-service/judge-queue-service.service.ts
> +            return (await client.brpop(JudgeQueueService.pendingQueue, 0))[1];
[blpop#blocking-behavior](https://redis.io/commands/blpop#blocking-behavior)

```
If none of the specified keys exist, BLPOP blocks the connection until another client performs an LPUSH or RPUSH operation against one of the keys.

A timeout of zero can be used to block indefinitely.😄️
```

2021-02-06 03:51 UTC, fitenne commented on src/scheduler/judger-pool/judger-pool.service.ts
> +            if (ret === undefined) {
fixed

2021-02-06 08:48 UTC, Nugine requested changes

2021-02-06 08:48 UTC, Nugine commented on src/scheduler/scheduler.debug.controller.ts
> +import CreateJudgeRequest = ExternalProtocol.Post.CreateJudgeRequest;
协议仓库已更新，现在可以用最新的定义了

2021-02-06 08:59 UTC, Nugine commented
各位检查一下还有没有要改的。
PR 作者改完后及时 Resolve conversation，reviewer 如果要求进一步改动，可以 Unsolve conversation。
明天我将合并此 PR，请 @Flaryer  #16  做好对接准备。

可以提前把分支拉下来测试有没有合并冲突

```bash
git checkout -b fitenne-master master
git pull https://github.com/fitenne/heng-controller.git master
```

2021-02-06 09:01 UTC, Nugine commented on src/scheduler/judger-pool/judger-pool.service.ts
> +    async login(judgerId: string, capacity: number): Promise<number> {
@A0nameless0man 以后要改的时候再想办法吧

2021-02-06 09:06 UTC, Nugine commented on src/scheduler/judge-queue-service/judge-queue-service.service.ts
> +            return (await client.brpop(JudgeQueueService.pendingQueue, 0))[1];
我觉得这里改不改都行

2021-02-06 09:20 UTC, Nugine commented
PR 作者改完后在对应的讨论里面回复一下 fixed by 1ce96b9 之类的，然后再 resolve，这样看邮件找上下文会方便一些。

2021-02-06 09:20 UTC, Nugine approved these changes

2021-02-07 01:50 UTC, merged

2021-02-09 05:31 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        while (true) {
有个问题，执行redis命令时是有可能抛出错误的（如键的类型和命令接受的类型不同），那么这个错误会被抛到getToken外面去（因为这里没有拦截）。
这里调用的时候外面（run函数）加了异常拦截，但是以后调用在其他地方会不会出问题。
所以我感觉有while的地方都要加异常拦截👀

2021-02-09 05:52 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +        while (true) {
再想想问题好像也不是非常大，因为之前加异常拦截是因为while不能断，这里没这个需求🤐

2021-02-09 05:56 UTC, Flaryer commented on src/scheduler/judger-pool/judger-pool.service.ts
> +                await this.redisService.client.sismember(
但是假如这里异常了，这个令牌就丢失了