内部通信模块
ThinkSpiritLab/heng-controller pull request #16
Opened 2021-01-30 07:06 UTC by Flaryer

内部通信模块，尚未引用协议仓库。

2021-01-31 12:45 UTC, A0nameless0man approved these changes, later dismissed

2021-01-31 13:52 UTC, Nugine requested changes

2021-01-31 13:52 UTC, Nugine commented on src/judger/judger.gateway.ts
> +        setInterval(async () => {
此处每个setTimeout 或 setInterval 里面的一大段匿名函数应当拆分为单独的成员方法。例如：

```ts
// 定期注册本进程心跳
setInterval(() => this.processHeartBeat(), this.judgerConfig.processPingInterval)
```

2021-01-31 13:52 UTC, Nugine commented on src/judger/judger.gateway.ts
> +        ) {
if 内部的多行条件应当拆分为单个有意义的变量，例如：
```ts
const isInvalidConnection = ...
if (isInvalidConnnection) {
   ...
}
```

2021-01-31 13:52 UTC, Nugine commented on src/judger/judger.gateway.ts
> +    };
像这样的RPC具体功能其实都应该拆出来放在 judgerService 里面，gateway 只处理与消息、连接有关的部分，service 去管理信息和状态。

2021-01-31 13:52 UTC, Nugine commented on src/judger/judger.gateway.ts
> +                let output: unknown;
output 是 Promise 还是 object ？
写个用来构造 res 的匿名函数，在 switch case 里面就把 output 转成 res，这样类型就能得到检查。

2021-01-31 13:52 UTC, Nugine commented on src/judger/judger.service.ts
> +    // 此 provider 目前闲置
部分方法应该写到这里来

2021-01-31 14:08 UTC, Flaryer commented on src/judger/judger.gateway.ts
> +                let output: unknown;
await 忘记加了）
匿名函数可能需要一点指导😢

2021-01-31 14:48 UTC, Nugine commented on src/judger/judger.gateway.ts
> +                let output: unknown;
大概这么写

```ts
export type ControllerRequest = ExitRequest | LogRequest | ReportStatusRequest | UpdateJudgesRequest | FinishJudgesRequest;
```

```ts
    private async handleRequest(ws: WebSocket, wsId: string, req: ControllerRequest): Promise<void> {
        const buildRes = <R>(body: Response<R>["body"]): Response<R> => ({
            type: "res",
            time: moment().format("YYYY-MM-DDTHH:mm:ssZ"),
            seq: req.seq,
            body,
        });

        const reply = async <R>(f: () => Promise<R>): Promise<void> => {
            let res;
            try {
                res = buildRes({ output: await f() });
            } catch (e) {
                res = buildRes({
                    error: {
                        code: 500,
                        message: e.message
                    }
                });
            }
            ws.send(JSON.stringify(res))
        };

        if (req.body.method === "Exit") {
            const args: ExitArgs = req.body.args;
            await reply(() => this.solveExit(ws, wsId, args));
        } else if (req.body.method === "Log") {
            const args: LogArgs = req.body.args;
            await reply(() => this.solveLog(ws, wsId, args));
        } 
        else if(...){
            ...
        }
        else {
            const res = buildRes({
                error: {
                    code: 400,
                    message: "error method"
                }
            })
            ws.send(JSON.stringify(res));
        }
    }
```

2021-02-01 08:56 UTC, fitenne approved these changes

2021-02-01 09:04 UTC, fitenne approved these changes, later dismissed

2021-02-01 12:28 UTC, Nugine requested changes

2021-02-01 12:28 UTC, Nugine commented on src/judger/judger.gateway.ts
> +    private processPing = async (): Promise<void> => {
这里还是写正常的成员方法吧，processPing 会被编辑器识别为成员变量。上面 setInterval 时注意 this 指向问题。

2021-02-01 12:28 UTC, Nugine commented on src/judger/judger.gateway.ts
> +    private getListenMessageQueue(
同样，这里其实不用返回一个函数，写普通的成员方法即可，在上面注册到 client 时可以写匿名函数。

2021-02-01 12:28 UTC, Nugine commented on package.json
> -        "heng-protocol": "https://github.com/ThinkSpiritLab/Heng-Protocol.git",
等 https://github.com/ThinkSpiritLab/Heng-Protocol/pull/5 合并后，这里可以引用协议仓库，同时移除这边的定义。

2021-02-02 15:12 UTC, Nugine requested changes
还有一处风格问题，改完后请等待 #14 合并。

2021-02-02 15:12 UTC, Nugine commented on src/judger/judger.gateway.ts
> +            client.on("error", this.getSolveError(client, token));
注册回调可以这么写，相关方法都写成普通成员方法。
```ts
            client.on("message", (msg: string) =>
                this.wsOnMessage(client, token, msg)
            );
            client.on("close", (code, reason) =>
                this.wsOnClose(client, token, code, reason)
            );
            client.on("error", e => this.wsOnError(client, token, e));
```

2021-02-03 13:47 UTC, Nugine submitted a review, later dismissed

2021-02-04 07:21 UTC, A0nameless0man submitted a review, later dismissed

2021-02-07 18:54 UTC, Flaryer commented on src/scheduler/scheduler.service.ts
> +                // FIXME taskId 不安全
@A0nameless0man @Nugine 有什么好办法吗，目前无法高效地可靠地将元素从list移动到set，目前想到lua脚本（存在其他障碍），或者先使用rpoplpush到list，然后再搞复杂的验证😅

2021-02-08 01:34 UTC, A0nameless0man commented on src/scheduler/scheduler.service.ts
> +                // FIXME taskId 不安全
哪个list到哪个set

2021-02-08 01:38 UTC, Flaryer commented on src/scheduler/scheduler.service.ts
> +                // FIXME taskId 不安全
任务队列 到 某评测机拥有的任务的set
可以尝试先获取令牌，再获取任务，这样才能知道放到哪个set，也不会死锁。

2021-02-09 02:30 UTC, A0nameless0man commented on src/scheduler/scheduler.service.ts
> +                // FIXME taskId 不安全
后一个set可以改用list
查询和删除的复杂度正比于list长度

2021-02-09 03:40 UTC, fitenne commented on src/scheduler/scheduler.service.ts
> +                // FIXME taskId 不安全
> 任务队列 到 某评测机拥有的任务的set
> 可以尝试先获取令牌，再获取任务，这样才能知道放到哪个set，也不会死锁。

获取到令牌后，发任务之前评测机掉线了怎么办。测试的时候发现了这个问题，好像忘记修了。🙏🏻️

当时想可以先获取任务再获取令牌，现在想想先获取任务再获取令牌也无法解决问题。

可不可以把对评测机掉线的处理放到调度这边。

调度这边实现一种检查的机制，对于一个被下发的任务，若一段时间后该任务没有被完成，检查其对应的评测机的状态，从而决定是不是需要回收并重新调度任务。

2021-02-09 03:44 UTC, Flaryer commented on src/scheduler/scheduler.service.ts
> +                // FIXME taskId 不安全
> 发任务之前评测机掉线了怎么办。
@fitenne 
我那边会检测评测机状态，会throw，令牌会被重新塞入令牌队列，在下次取出的时候被丢弃。
```ts
if (token) await this.judgerPoolService.releaseToken(token, 1);
```

2021-02-09 03:54 UTC, Flaryer commented on src/scheduler/scheduler.service.ts
> +                // FIXME taskId 不安全
实际上直到任务完全下发到评测机，都出了问题会throw，所以现在只有taskid不安全的问题

2021-02-09 04:55 UTC, Flaryer commented on src/judger/judger.service.ts
> +        // if (!infoStr) throw new Error(`taskId: ${taskId} 找不到 JudgeInfo`);
若找不到 JudgeInfo：
1. 因为 bug 任务被发放两次 
2. 因为 bug，JudgeInfo 没有被记录。

这些任务应当被抛弃，否则陷入死循环。

目前没有合理的机制来抛弃此任务，是利用函数返回值还是为Error设置错误类型之类的呢？
@A0nameless0man @Nugine @fitenne

2021-02-09 05:04 UTC, Flaryer commented on src/judger/judger.service.ts
> +        // if (!infoStr) throw new Error(`taskId: ${taskId} 找不到 JudgeInfo`);
或者开个hash/set之类的，标记此任务无效，发放任务之前检查。

2021-02-10 08:10 UTC, Nugine reviewed
1. 修复配置，要求在 git clone 下来后不做任何更改即可运行
2. 给出测试方法
3. 写出对 #14 内容所做更改的大概原理

2021-02-10 08:10 UTC, Nugine commented on src/config/config.ts
> +    public readonly scheduler!: SchedulerConfig;
为子模块配置都加上 `@IsNotEmpty()`

2021-02-10 08:10 UTC, Nugine commented on src/config/judger.config.ts
> +    webSocketPath!: string;
这个配置项是用来做什么的？

2021-02-10 08:50 UTC, Flaryer commented on src/config/judger.config.ts
> +    webSocketPath!: string;
```ts
        const isPathCorrect =
            req.url && req.url.startsWith(this.judgerConfig.webSocketPath);
        const isTokenVaild = await this.checkTokenVaild(token, ip);
        if (!isPathCorrect || !isTokenVaild) {
            client.close();
            client.terminate();
            return;
        }
```
检测path的。

2021-02-10 09:07 UTC, Nugine commented on src/config/judger.config.ts
> +    webSocketPath!: string;
为什么这里需要检查

2021-02-10 09:08 UTC, Flaryer commented on src/config/judger.config.ts
> +    webSocketPath!: string;
emmm，不是协议里面评测机连接的时候有path要求吗

2021-02-10 09:15 UTC, Flaryer commented
1. 测试方法：debug并没有删（主要位于SchedulerService内），若redis中设置了addTask键，每个进程启动会推入20000个随机任务。评测机（简单评测机位于文档结尾）连接后自动分发，任务全部分发完可以看一看redis内”pendingTask“内有无任务，有任务说明丢任务了。为了寻找bug，可以在电脑性能允许的情况下（评测机很吃电脑性能，可以考虑双机），任意逐个/批量reload控制端或者reload评测机等。
2. #14 
- 填充了run函数，持续分发任务
- 去除logout函数中抛出异常,（见注释）
- getToken函数while中加了异常检测，防止丢令牌
- releaseToken函数加了capacity参数，用于一次恢复多个令牌
- 修改pop函数，分发任务流程为利用brpoplpush将taskId推入一个备份队列（队列名随机且包含时间戳），确定任务发放出去后，删除此备份队列。另外定时检测所有的备份队列，若”超时“则恢复备份队列中任务。故pop函数还返回该备份队列的名字。pop函数也添加了异常检测，防止丢taskId。
- pop函数添加检查任务是否无效，无效则丢弃，同时从黑名单中删除taskId。程序定时清理黑名单。
- push函数添加：从黑名单中去除push过来的taskId

2021-02-10 09:47 UTC, Nugine commented on src/config/judger.config.ts
> +    webSocketPath!: string;
[docs/internal-protocol.md#websocket](https://github.com/ThinkSpiritLab/Heng-Protocol/blob/master/docs/internal-protocol.md#websocket-%E6%B6%88%E6%81%AF%E6%A0%BC%E5%BC%8F)

ws 地址是固定的，应当硬编码。
ws gateway 装饰器里面的 options 是给 socket.io 用的，对 platform-ws 不会生效，应该删除那里的参数。
这里检查 path 是正确的，但不是用 startsWith，而是完全匹配。

2021-02-12 05:27 UTC, A0nameless0man commented on src/config/judger.config.ts
> +    webSocketPath!: string;
我记得有合适的装饰器参数。

2021-02-12 05:29 UTC, A0nameless0man commented
测试可以使用 Heng-Client , 目前的开发进度在 [https://github.com/A0nameless0man/Heng-Client](我的fork里)

2021-02-12 06:09 UTC, Nugine commented
明天晚上我将合并该 PR，请 author 和各位 reviewer 再次检查。

2021-02-12 06:12 UTC, Nugine commented
> 测试可以使用 Heng-Client , 目前的开发进度在 https://github.com/A0nameless0man/Heng-Client

这个怎么运行，来点简单文档

2021-02-12 06:22 UTC, Nugine approved these changes, later dismissed

2021-02-12 15:05 UTC, Flaryer commented
修复数个bug：
- redis断联可能出现的问题
- wsOnClose调用失败可能出现的问题
- 去除重新分配任务时用到的“锁”，以避免其他的时序问题，使用任务黑名单代替。
- 评测机上线后进程进行心跳，以免进程一次心跳都没有记录，导致进程不被清理

2021-02-13 07:10 UTC, Nugine requested changes

2021-02-13 07:10 UTC, Nugine commented on src/judger/judger.controller.ts
> +    ): Promise<AcquireTokenOutput | ErrorInfo> {
应该是 Post。原因有三个：
1. 通信协议规定为 Post
2. HTTP GET 虽然没有规定不能带 body，但不是所有客户端实现都支持 GET body。
3. 获取 token 这一操作不满足幂等性。

另外 body 应当加上校验。

2021-02-13 11:50 UTC, Nugine submitted a review, later dismissed

2021-02-13 15:13 UTC, A0nameless0man requested changes

2021-02-13 15:13 UTC, A0nameless0man commented on src/judger/judger.gateway.ts
> +     * 评测机池 please fill this
这一行是否已可以移除？

2021-02-13 15:13 UTC, A0nameless0man commented on src/judger/judger.gateway.ts
> +     * 评测机池 please fill this
同，是否可移除？

2021-02-13 15:13 UTC, A0nameless0man commented on src/judger/judger.gateway.ts
> +     * @param wsId
少参数

2021-02-13 15:13 UTC, A0nameless0man commented on src/judger/judger.gateway.ts
> +        while (ws && ws.readyState <= WebSocket.OPEN) {
真的要对枚举值用比较吗，或者加个注释吧

2021-02-13 15:13 UTC, A0nameless0man commented on src/judger/judger.gateway.ts
> +        }`;
请不要滥用三元运算符……

2021-02-13 15:13 UTC, A0nameless0man commented on src/judger/judger.gateway.ts
> +     * @param wsId
少参数

2021-02-13 15:13 UTC, A0nameless0man commented on src/judger/judger.gateway.ts
> +     * @param wsId
少参数

2021-02-13 15:13 UTC, A0nameless0man commented on src/judger/judger.gateway.ts
> +     * @param wsId
少参数

2021-02-14 04:17 UTC, Nugine approved these changes

2021-02-15 01:56 UTC, A0nameless0man approved these changes

2021-02-15 01:59 UTC, A0nameless0man commented
话说，为何config文件被从gitignore中移除了
我的测试环境中，8080端口已占用，redis不在本机……

2021-02-15 02:01 UTC, Flaryer commented
> 话说，为何config文件被从gitignore中移除了
> 我的测试环境中，8080端口已占用，redis不在本机……

https://github.com/ThinkSpiritLab/heng-controller/pull/16#pullrequestreview-587332146

2021-02-15 02:37 UTC, fitenne approved these changes

2021-02-15 03:02 UTC, Nugine commented
> 话说，为何config文件被从gitignore中移除了
> 我的测试环境中，8080端口已占用，redis不在本机……

1. 仓库中的 config 应该是默认配置，而不是示例配置。
2. 如果用 git 管理部署版本，忽略 config 会造成难以追踪配置变化的问题，无法回滚或比对。
3. 对于测试环境与默认配置不符的情况，应该开一个具有不同配置的本地分支，从要测试的分支合并代码，冲突时保留自己对配置的更改。

2021-02-15 03:10 UTC, Nugine commented
> 话说，为何config文件被从gitignore中移除了
> 我的测试环境中，8080端口已占用，redis不在本机……

后面可以加个从命令行读取配置文件路径

2021-02-15 03:11 UTC, merged