没有写完
ThinkSpiritLab/heng-controller pull request #17
Opened 2021-02-16 01:11 UTC by revue-starlight

不太会写，会继续写。dbq

2021-02-16 02:27 UTC, A0nameless0man commented on .eslintrc.js
> +        "linebreak-style": ["off", "windows"],
不要瞎搞，vscode有改变换行模式的选项

2021-02-16 02:28 UTC, A0nameless0man commented on src/external-module/external-module.controller.ts
> +    async JudgeLogin(@Req() request: any): Promise<any> {
外部模块不负责judger啊……

2021-02-16 02:30 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +        if ((await this.redisService.client.get("Taskids")) == null)
redis对于整数的操作提供不少原子方法，请看文档。

2021-02-16 02:31 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +        //Q:评测机直接调用url还是在这里调用呢？
提供一个方法供内部模块调用

2021-02-16 02:32 UTC, A0nameless0man commented on tsconfig.json
> +        "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
为啥改这个？

2021-02-16 02:32 UTC, A0nameless0man commented on yarn.lock
> +<<<<<<< HEAD
冲突了，兄弟……

2021-02-16 03:34 UTC, Nugine commented
我们之前没有具体规定外部交互模块的行为，作者可以先写一下这个PR做了哪些改进，方便讨论。

没有完成的PR可以转换为 draft 模式，自动测试一样会运行，reviewer 也可以看到代码。完成后可以退出draft模式。

请不要改动编译配置和格式化配置，除非发生了什么冲突或者特殊问题。如果有，要在PR中说明一下。

2021-02-16 03:56 UTC, revue-starlight commented on .eslintrc.js
> +        "linebreak-style": ["off", "windows"],
嗯，修改了

2021-02-16 03:56 UTC, revue-starlight commented on src/external-module/external-module.controller.ts
> +    async JudgeLogin(@Req() request: any): Promise<any> {
这里的原来的想法是评测端用http post登录,然后返回token，然后建立连接。是不是有啥问题....

2021-02-16 03:56 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +        if ((await this.redisService.client.get("Taskids")) == null)
谢谢qaqaqaqaqaqaq

2021-02-16 03:56 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +        //Q:评测机直接调用url还是在这里调用呢？
嗯嗯

2021-02-16 03:56 UTC, revue-starlight commented on yarn.lock
> +<<<<<<< HEAD
嗯..

2021-02-16 04:00 UTC, revue-starlight commented on tsconfig.json
> +        "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
这个之前注释掉会谜之报错。。。但是现在好像又好了

2021-02-16 10:25 UTC, A0nameless0man commented on src/external-module/external-module.controller.ts
> +    async JudgeLogin(@Req() request: any): Promise<any> {
确实是这个流程，但是这部分工作是由内部模块负责处理的。

2021-02-16 10:27 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +        //Q:评测机直接调用url还是在这里调用呢？
具体而言，评测机会通过wsrpc通知控制端。内部模块收到通知后，会调用外部模块提供的方法。外部模块进行实际的HTTP回调。

2021-02-16 10:53 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +        if ((await this.redisService.client.get("Taskids")) == null)
又及，这是不是某种全局自增主键？

2021-02-16 11:27 UTC, Nugine commented
目前[外部通信协议](https://github.com/ThinkSpiritLab/Heng-Protocol/blob/master/docs/external-protocol.md)定义了两个接口。PR 作者需要实现这两个接口。

内部通信模块要在某个 service 中提供读取评测端状态的方法。

外部通信模块增加一个 service，实现：
1. 读取控制端状态
2. 保存评测任务信息，把任务ID传递给评测队列

增加一个 controller，实现：
1. 查询系统负载接口：用对应的 service 取得控制端和评测端的状态信息，返回状态信息
2. 创建评测任务接口：用对应的 service 把评测任务传递给评测队列，返回这个任务的ID

@revue-starlight @Flaryer 你们讨论一下怎么对接

2021-02-16 11:41 UTC, Flaryer commented
外部通信还需要两个接口：汇报任务状态和任务结果（由内部通信调用，调用后将状态或者结果发送给给定的url）。具体见下图。
![process](https://user-images.githubusercontent.com/30646834/108058245-b63c3c80-708e-11eb-8f3e-37dbb0e51f46.gif)


另外获取评测机状态和控制端状态是否属于管理员接口了。 @Nugine

2021-02-16 11:46 UTC, Nugine commented
> 外部通信还需要两个接口：汇报任务状态和任务结果（由内部通信调用，调用后将状态或者结果发送给给定的url）。具体见下图。
> ![process](https://user-images.githubusercontent.com/30646834/108058245-b63c3c80-708e-11eb-8f3e-37dbb0e51f46.gif)
> 
> 另外获取评测机状态和控制端状态是否属于管理员接口了。 @Nugine

查询状态属于管理接口，可以拆到另一个 controller

2021-02-16 13:44 UTC, A0nameless0man commented
管理接口好像一开始说由各个模块自行提供，不进行集中。
另外，有人记得Guard模块谁来写吗。

2021-02-16 13:45 UTC, Flaryer commented
我记得Guard还没人接锅

2021-02-16 16:31 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +        if ((await this.redisService.client.get("Taskids")) == null)
嗯，已经将自增改为client.incr()。不过redis的值好像只能存储字符串

2021-02-16 23:37 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +        if ((await this.redisService.client.get("Taskids")) == null)
JudgeLogin Exit getLog reportStatus createjudge这几个函数都和内部通信重复了。外部通信只负责和oj的web端通信，只用于和web端收发任务，回报任务状态；不负责管理/操纵评测机，不负责和评测机通信。
另外各模块的管理员接口是分开提供的吗
@Nugine 
另外收到任务之后，taskid要自动生成吗，还是用web端提供的taskid。 @A0nameless0man @Nugine

2021-02-17 02:04 UTC, revue-starlight commented
嗯...------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Flaryer&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月17日(星期三) 上午7:37
收件人:&nbsp;&quot;ThinkSpiritLab/heng-controller&quot;<heng-controller@noreply.github.com&gt;;
抄送:&nbsp;&quot;revue-starlight&quot;<204214884@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ThinkSpiritLab/heng-controller] 外部交互模块（没有写完） (#17)

2021-02-17 02:43 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +        if ((await this.redisService.client.get("Taskids")) == null)
web端好像没有提供taskid，应该是外部模块这里提供

2021-02-17 07:51 UTC, Nugine commented on src/external-module/external-module.service.ts
> +        if ((await this.redisService.client.get("Taskids")) == null)
管理接口分开提供。

外部系统发的请求中携带了id，外部通信模块需要对这个输入的id做重新映射，生成一个内部使用的taskId，以免不同的外部系统之间发生冲突，给外部系统发回调时还是用原来输入的id。

https://github.com/ThinkSpiritLab/Heng-Protocol/blob/239ab32b44e5531094b37b5262ca5f573d93a11a/external-protocol/index.ts#L19

2021-02-17 08:27 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +        if ((await this.redisService.client.get("Taskids")) == null)
按照我的理解，外部系统只要自己把id编码到回调url里即可。发来的请求不需要包含id

2021-02-17 08:44 UTC, Nugine commented on src/external-module/external-module.service.ts
> +        if ((await this.redisService.client.get("Taskids")) == null)
这样也可以，先按内部生成taskId写，忽略有关外部id的内容。

2021-02-19 15:58 UTC, revue-starlight commented on tsconfig.json
> +        "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
> 为啥改这个？

找到报的错了，在import { 一些东西 } from “src/一些东西" 时，路径"src/一些东西"会报错

2021-02-26 14:05 UTC, A0nameless0man approved these changes

2021-02-27 02:10 UTC, Flaryer requested changes

2021-02-27 02:10 UTC, Handgrip commented on src/judger/judger.service.ts
> +        this.externalmoduleService.responsefinish(
await

2021-02-27 02:10 UTC, Handgrip commented on src/judger/judger.service.ts
> +        this.externalmoduleService.responseupdate(
await

2021-02-27 02:10 UTC, Handgrip commented on src/judger/judger.service.ts
> +            vaildResult
上面solveUpdateJudges()也是这个情况：
vaildResult的类型：
```ts
const vaildResult: {
    id: string;
    result: JudgeResult;
}[]
//or
const vaildResult: FinishJudgesArgs
```
这个时候只能调用vaildResult了，不能调用args了。另外这是一个数组，应当在this.externalmoduleService.responsefinish内循环处理这个数组。

2021-02-27 02:10 UTC, Handgrip commented on src/external-module/external-module.service.ts
> +            )[0] || "";
这边假如是null，应该throw或者continue吧。推荐continue，因为这个时候此任务已经报废了。
上面也是这样。

2021-02-27 02:10 UTC, Handgrip commented on src/external-module/external-module.service.ts
> +        result: FinishJudgesArgs
此处参数类型：
```ts
vaildResult: {
    id: string;
    result: JudgeResult;
}[]
//or
vaildResult : FinishJudgesArgs
```

另外函数内部应当循环处理此数组。
上面也是这样。

2021-02-27 02:10 UTC, Handgrip commented on src/judger/judger.service.ts
> +        // ) {
既然上面复制了这里原来的注释，原来的注释其实不动就行。
另外这个pendingTask是debug用的；另外改完之后注释内应该花括号不匹配。

2021-02-27 02:10 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +        await this.redisService.client.hmset(
hset
上面也是

2021-02-27 02:10 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +        return inreq;
这里返回类型CreateJudgeRequest，下面getJudgeINFO()返回CreateJudgeArgs，写入读出的类型都不一样。
所以这里返回inreq.body.method就行。其他多余的都可以删掉，比如this.keys.Seq。

2021-02-27 02:10 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +        await this.redisService.client.incr(this.keys.Seq);
可能是重复or多余语句

2021-02-27 02:10 UTC, Flaryer commented on src/external-module/external-module.controller.ts
> +    async CreateJudgeReq(@Body() req: CreateJudgeRequest): Promise<void> {
class-vaildator还没加

2021-02-27 02:18 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +        await this.redisService.client.incr(this.keys.Seq);
猜测这里为this.keys.Taskseq，如果是请使用redis事务（this.redisService.client.multi()）把下面一行和这一行连起来。

2021-02-27 02:49 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +        await this.redisService.client.incr(this.keys.Seq);
incr返回加一后该键的值

2021-02-27 07:04 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +        result: FinishJudgesArgs
好像已经删除了批量请求，validResult不是数组了，但是协议还没来的及改。。 @A0nameless0man 麻烦确认一下是不是这样

2021-02-28 03:51 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +        result: FinishJudgesArgs
批量请求已从设计中移除

2021-02-28 03:55 UTC, Flaryer commented on src/judger/judger.service.ts
> +            vaildResult
https://github.com/ThinkSpiritLab/heng-controller/pull/17#discussion_r584066436

协议仓库貌似还没改，那这里就先改成仅使用`vaildResult[0]`。

2021-02-28 04:05 UTC, A0nameless0man requested changes

2021-02-28 04:05 UTC, A0nameless0man commented on docs/外部通信模块.md
> +'externalmodule:calbckurl:upd' : taskid - url 用于存放回调任务状态的url
此处记录的键值与代码中不一致，包括下面几行，请修正

2021-02-28 04:05 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +import * as external from "heng-protocol/external-protocol";
请明确所引用的内容，这里好像只引用了一个类型。
`import { CreateJudgeRequest} from "heng-protocol/external-protocol";`

2021-02-28 04:05 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +            time: moment().format("YYYY-MM-DDTHH:mm:ssZ")
`new Date().toISOString()` 即可

2021-02-28 04:05 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +            time: moment().format("YYYY-MM-DDTHH:mm:ssZ")
不需要添加不必要的依赖

2021-02-28 04:05 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +    async judgereqconvert(
这个函数的功能有问题，外部模块需要将请求中的评测信息存储到Redis中，但是将其包装为内部通信的格式这个工作是内部模块进行的。

2021-02-28 04:05 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +        this.logger.log("发送评测任务 id: ${taskid} ");
应该是评测任务已进入队列

2021-02-28 04:05 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +            )[0] || "";
此处如果null了，建议打个Warning

2021-02-28 04:07 UTC, A0nameless0man commented on src/external-module/external-module.controller.ts
> +    async CreateJudgeReq(@Body() req: CreateJudgeRequest): Promise<void> {
需要的元数据尚未添加至协议仓库

2021-02-28 04:11 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +            time: moment().format("YYYY-MM-DDTHH:mm:ssZ")
Date不行，之前测试，出来的时间是+0时区，而不是+8

2021-02-28 06:56 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +import * as external from "heng-protocol/external-protocol";
明确的话会和Internal-protocol里的CreateJudgeRequest冲突，有没有什么好方法解决呢？。。。

2021-02-28 06:56 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +import * as external from "heng-protocol/external-protocol";
明确的话会和Internal-protocol里的CreateJudgeRequest冲突，有没有什么好方法解决呢？。。。

2021-02-28 07:09 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +import * as external from "heng-protocol/external-protocol";
明白了，不需要做协议转换以后就没有这个问题了

2021-02-28 08:44 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +        await this.axiosService.post(url, { taskid, state });
由上文得知CalbckURLUpd有可能为undefined，这里应该缺少相应判断。

2021-02-28 08:46 UTC, Flaryer requested changes
另外缺少redis相应key的垃圾清理，比如任务完成后删除CalbckURLUpd，麻烦点的可能包括异常任务的垃圾清理。

2021-02-28 10:01 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +        return inreq;
因为是直接传Args，这里会有较大的删除

2021-02-28 10:14 UTC, Nugine commented on src/external-module/external-module.service.ts
> +        await this.axiosService.post(url, { taskid, state });
CalbckURLUpd 这命名是缩写还是typo？就算缩写也没有这种扣掉两个字母的写法……

2021-02-28 14:13 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +        await this.axiosService.post(url, { taskid, state });
> CalbckURLUpd 这命名是缩写还是typo？就算缩写也没有这种扣掉两个字母的写法……

查阅了资料，callback是cb。。

2021-03-01 03:26 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +import * as external from "heng-protocol/external-protocol";
`import { CreateJudgeRequest as XXX} from "heng-protocol/external-protocol";`

2021-03-01 03:26 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +            time: moment().format("YYYY-MM-DDTHH:mm:ssZ")
难顶，确实

2021-03-01 03:28 UTC, A0nameless0man commented
> 另外缺少redis相应key的垃圾清理，比如任务完成后删除CalbckURLUpd，麻烦点的可能包括异常任务的垃圾清理。

异常任务指哪些情形呢？如果评测机掉线等会重测，任务无法实际执行会产生SE，仍然会报告结果。

2021-03-01 03:37 UTC, Flaryer commented
> > 另外缺少redis相应key的垃圾清理，比如任务完成后删除CalbckURLUpd，麻烦点的可能包括异常任务的垃圾清理。
> 
> 异常任务指哪些情形呢？如果评测机掉线等会重测，任务无法实际执行会产生SE，仍然会报告结果。

可以认为任务最终如果汇报了结果，那么外部交互中相应key会被清理。
目前会主动丢弃任务的情况有
1. 无法获取judgeInfo，此情况任务id会进入黑名单，再次取出此任务时会从任务队列中删除此id。相应代码位于 https://github.com/ThinkSpiritLab/heng-controller/blob/master/src/scheduler/judge-queue-service/judge-queue-service.service.ts#L78 以下。可考虑扩充84行完成对cbURL的清理。
2. 待发现

2021-03-05 13:21 UTC, Nugine requested changes
1. 命名风格不统一，最好改改。
2. 除非万不得已，不要使用 any。
3. 由于 yarn v1 的 bug，协议仓库不能自动编译，切换为 npm 吧。具体步骤：删掉 yarn.lock，npm install，提交 package-lock.json。
4.  @Flaryer @revue-starlight 移除批量更新后的改动不大，确认解决后就 resolve conversation

如果周末解决了所有问题，我将于下周一晚上合并此 PR。

2021-03-05 13:21 UTC, Nugine commented on src/external-module/external-module.controller.ts
> +    async CreateJudgeReq(@Body() Body: CreateJudgeRequest): Promise<any> {
不要使用 any，这里应该可以写出类型

2021-03-05 13:21 UTC, Nugine commented on src/external-module/external-module.service.ts
> +        const url: any = (
同上，不要使用 any

2021-03-05 13:21 UTC, Nugine commented on src/external-module/external-module.service.ts
> +    async createjudge(req: CreateJudgeRequest): Promise<void> {
为什么用两个单词拼起来的命名？js 的类方法命名通常使用小驼峰。

2021-03-05 13:21 UTC, Nugine commented on src/external-module/external-module.service.ts
> +    ): Promise<any> {
any...

2021-03-05 13:21 UTC, Nugine commented on src/external-module/external-module.service.ts
> +    async getJudgeINFO(taskId: string): Promise<CreateJudgeArgs> {
INFO 为啥大写...

2021-03-07 01:41 UTC, Flaryer requested changes
另外貌似TaskTime还没利用到，应该是垃圾清理相关的。

2021-03-07 01:41 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +        await mu.exec();
官方教程里没说用mu存储multi并且包含多个语句时该怎么写，但是我感觉这里什么语句都不会执行（我也还没测试）。应该是mu=mu.hmset(...);
或者直接链式。
另外为啥还是hmset，下面还有hmget，虽然没什么大影响。

2021-03-07 01:41 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +            await mu.exec();
同上

2021-03-07 01:41 UTC, Flaryer commented on src/judger/judger.service.ts
> +        // ) {
我好像没法resolve这段对话😲

2021-03-07 01:41 UTC, Flaryer commented on src/judger/judger.service.ts
> +            vaildResult
https://github.com/ThinkSpiritLab/heng-controller/pull/17/files#r584228100 别用args数组啦，vaildResult是args筛出来的呀，另外判断一下vaildResult的长度。

2021-03-07 01:41 UTC, Flaryer commented on docs/外部通信模块.md
> +'Ext:JudgeINFO' : taskid - JSON.stringify(Internal.CreateJudgeRequest) 用于存放评测任务信息
是CreateJudgeArgs

2021-03-07 01:41 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +            moment().format("YYYY-MM-DDTHH:mm:ssZ")
我认为这种不给人看的时间设置成timestamp就好，Date.now()，方便读取，比较。

2021-03-07 01:43 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +            await mu.exec();
然后这里是hdel。。。你这样把整个hash键删了啊

2021-03-07 16:22 UTC, revue-starlight commented
确实（------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Flaryer&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月7日(星期天) 上午9:43
收件人:&nbsp;&quot;ThinkSpiritLab/heng-controller&quot;<heng-controller@noreply.github.com&gt;;
抄送:&nbsp;&quot;revue-starlight&quot;<204214884@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ThinkSpiritLab/heng-controller] 外部交互模块 (#17)

2021-03-07 16:26 UTC, revue-starlight commented
judger那一段代码我不太熟悉，删除了多组评测后，我改的应该不太好。麻烦大家再查看一下。    其他的都作出了修改，如果有不完善的地方还请指正。谢谢各位大佬～。🌸------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Nugine&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月5日(星期五) 晚上9:21
收件人:&nbsp;&quot;ThinkSpiritLab/heng-controller&quot;<heng-controller@noreply.github.com&gt;;
抄送:&nbsp;&quot;revue-starlight&quot;<204214884@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ThinkSpiritLab/heng-controller] 外部交互模块 (#17)

2021-03-07 16:57 UTC, revue-starlight commented on src/judger/judger.service.ts
> +        // ) {
对唔住..我也不太理解

2021-03-07 16:57 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +            await mu.exec();
mu=mu.hdel()

2021-03-07 16:59 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +            await mu.exec();
惊天大bug!!!!!!!

2021-03-07 16:59 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +    async getJudgeINFO(taskId: string): Promise<CreateJudgeArgs> {
dbq...不太熟悉风格

2021-03-07 17:00 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +        await mu.exec();
已修改

2021-03-07 17:00 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +        const url: any = (
嗯

2021-03-07 17:07 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +    async createjudge(req: CreateJudgeRequest): Promise<void> {
嗯，已修改

2021-03-07 21:19 UTC, A0nameless0man requested changes

2021-03-07 21:19 UTC, A0nameless0man commented on docs/外部通信模块.md
> +   将 external.CreateJudgeRequest 从外部通信协议格式存入 redis 中。并将其转化为 JSON 字符串，放入 redis 队列中。塞入评测队列。等待评测结果回调
将其转化为 JSON 字符串，放入hset，将id交给任务队列模块吧。

2021-03-07 21:19 UTC, A0nameless0man commented on src/external-module/external-module.controller.ts
> +    @Get("/test/:id")
建议换个人类可读的路径，比如 `/test/reportFinish/:id` 或 `/test/reportFinish/?id=:id`

2021-03-07 21:19 UTC, A0nameless0man commented on src/external-module/external-module.controller.ts
> +        console.log(Body);
请用nestjs提供的logger，请使用ts提供的字符串拼接方法

2021-03-07 21:19 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +        mu = mu.hmset(this.keys.TaskTime, req.id, Date.now());
确实没问题，但还是建议链式

2021-03-07 21:19 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +        req.id;
这一行是干啥？

2021-03-07 21:19 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +            mu.hdel(this.keys.TaskTime, taskid);
同样，建议链式调用

2021-03-07 21:19 UTC, A0nameless0man commented on src/judger/judger.service.ts
> +        mu = mu.sismember(wsId + WsOwnTaskSuf, args.id);
单个命令不需事务

2021-03-08 03:33 UTC, Nugine commented on src/external-module/external-module.controller.ts
> +    async CreateJudgeReq(
一般用小驼峰命名，首字母小写。

2021-03-08 03:45 UTC, Nugine commented on src/external-module/external-module.service.ts
> +        mu = mu.hmset(this.keys.TaskTime, req.id, Date.now());
hmset 可以一次性设置多个键值对

https://redis.io/commands/hmset

2021-03-08 05:27 UTC, revue-starlight commented
嗯...hmset好像只能批量键值，在不同的key里不能用...我这里要不还是改为hset吧------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Nugine&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月8日(星期一) 中午11:45
收件人:&nbsp;&quot;ThinkSpiritLab/heng-controller&quot;<heng-controller@noreply.github.com&gt;;
抄送:&nbsp;&quot;revue-starlight&quot;<204214884@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ThinkSpiritLab/heng-controller] 外部交互模块 (#17)

2021-03-08 07:04 UTC, A0nameless0man approved these changes, later dismissed

2021-03-08 14:39 UTC, Nugine submitted a review, later dismissed

2021-03-09 06:30 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +    public readonly keys = {
建议static，不然别的模块读不到

2021-03-09 06:39 UTC, Flaryer requested changes

2021-03-09 06:39 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +            this.logger.warn(`未找到更新状态id ${taskid} 的回调url`);
return;

2021-03-09 06:39 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +        )[0];
用hget好像返回的直接是value，不用加 [0]

2021-03-09 06:39 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +        )[0];
同上

2021-03-09 06:39 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +            this.logger.log(`已返回评测任务id: ${taskid} 的结果`);
删除console.log()

2021-03-09 06:39 UTC, Flaryer commented on src/judger/judger.service.ts
>          // TODO 通知外部系统
换为自己的函数。

2021-03-09 06:39 UTC, Flaryer commented on src/judger/judger.service.ts
>          // TODO 通知外部系统
换为自己的函数。

2021-03-09 06:55 UTC, revue-starlight commented
奇怪，我这个在本地改过了啊。...------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Flaryer&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月9日(星期二) 下午2:39
收件人:&nbsp;&quot;ThinkSpiritLab/heng-controller&quot;<heng-controller@noreply.github.com&gt;;
抄送:&nbsp;&quot;revue-starlight&quot;<204214884@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ThinkSpiritLab/heng-controller] 【功能模块开发】外部交互模块 (#17)

2021-03-09 06:58 UTC, revue-starlight commented
push不上去力，，，------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Flaryer&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月9日(星期二) 下午2:39
收件人:&nbsp;&quot;ThinkSpiritLab/heng-controller&quot;<heng-controller@noreply.github.com&gt;;
抄送:&nbsp;&quot;revue-starlight&quot;<204214884@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ThinkSpiritLab/heng-controller] 【功能模块开发】外部交互模块 (#17)

2021-03-09 08:37 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +    public readonly keys = {
其它模块也不该读这玩意啊

2021-03-09 08:41 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +    public readonly keys = {
其实，其它模块不应该读这些。

2021-03-09 08:44 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +    public readonly keys = {
方便以后修改吧，就像现在内部通信读了评测机池的键

2021-03-09 08:45 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +            this.logger.warn(`未找到更新状态id ${taskid} 的回调url`);
这个评论忽略，忘记删了，不用改。

2021-03-09 09:00 UTC, Flaryer requested changes

2021-03-09 09:00 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +        await this.judgequeueService.push(String(req.id));
这里不用string()了，上面有了。

2021-03-09 09:00 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +            this.cleanJudge(taskid);
建议这一行放在if else外面，防止跳过清理垃圾。

2021-03-09 09:00 UTC, Flaryer commented on src/judger/judger.gateway.ts
> +                    //reject(new Error("Empty Response"));
改成if else

2021-03-09 09:00 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +        state: UpdateJudgesArgs
仓库已经改了，这里state类型为JudgeState，调用时是args.state，下面finish函数也要改

2021-03-09 13:40 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +            this.cleanJudge(taskid);
好

2021-03-09 13:40 UTC, revue-starlight commented on src/external-module/external-module.service.ts
> +    public readonly keys = {
等到要读的时候再改也不迟

2021-03-09 14:04 UTC, Flaryer commented on src/external-module/external-module.service.ts
> +                );
有个问题：连接失败时应当throw，这将导致RPC失败，按照计划 @A0nameless0man 评测机那里会再次回报结果。因此这里不仅打log，还要throw。上面回报状态我不知道要不要这样，可能导致评测机那里结果回报了但是一堆状态未回报（非洲评测机）？问问 @A0nameless0man 怎么搞。

2021-03-16 07:30 UTC, A0nameless0man approved these changes, later dismissed

2021-03-19 14:04 UTC, Nugine commented on src/external-module/external-module.service.ts
> +                );
@A0nameless0man 评测机对这种情况是怎么处理的

2021-03-19 14:11 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +                );
这里回报失败我觉得不应当向评测机通报，应当由外部模块尽最大努力（指若干次重试）后放弃。

2021-03-19 14:13 UTC, A0nameless0man commented on src/external-module/external-module.service.ts
> +                );
同时，对评测机来说，这个上报的rpc调用应当尽快返回，因为评测机不关心对外部系统的调用是否成功。

2021-03-22 11:43 UTC, Nugine approved these changes

2021-03-22 11:45 UTC, Nugine commented
最后再确认一下，review 都通过后就合并。

2021-03-22 11:47 UTC, A0nameless0man approved these changes

2021-03-22 11:51 UTC, merged