Guard
ThinkSpiritLab/heng-controller pull request #19
Opened 2021-03-09 21:52 UTC by WanchengWildMan

guard附带一个简单的filter和pipe
每个接口的角色需要确定
日志的格式及数量

2021-03-10 00:05 UTC, Nugine commented
PR #19 的合并顺位在 #17 之后。
内容比较多，我可能过两天才有时间看完。

2021-03-16 07:21 UTC, A0nameless0man commented on POST
> + 4 files changed, 24 insertions(+), 11 deletions(-)
这是啥？

2021-03-16 07:21 UTC, A0nameless0man commented on package.json
> +  "name": "heng-controller",
发生了啥？

2021-03-17 07:57 UTC, A0nameless0man commented on src/auth/auth.guard.ts
> +            "roles",
1. 建议搞个私有或者公开的常量来代替代码中的字符串
2. 加个前缀以防止冲突比较好

2021-03-17 07:59 UTC, A0nameless0man commented on src/auth/auth.guard.ts
> +        const accessKey = req.headers[PublicHeadersType.accesskey] as string;
检查一下类型以避免 `as` ？

2021-03-17 08:03 UTC, A0nameless0man commented on src/auth/dto/roles.dto.ts
> +
空文件?

2021-03-19 06:54 UTC, Flaryer reviewed
好像缺文档

2021-03-19 06:54 UTC, Flaryer commented on src/auth/auth.decl.ts
> +    roles?: string[] | null;
RoleTypeArr[]

2021-03-19 06:54 UTC, Flaryer commented on src/auth/auth.filter.ts
> +            timestamp: new Date().toISOString(), // 错误日期
https://github.com/ThinkSpiritLab/heng-controller/pull/17#discussion_r584230228

2021-03-19 06:54 UTC, Flaryer commented on src/auth/auth.guard.ts
> +                    req.ip
忘了NGINX代理之后ip是什么了，可能是127.0.0.1，所以要用header['x-forward-for']或者header['x-real-ip']

2021-03-19 14:01 UTC, Nugine commented on src/auth/auth.decl.ts
> +}
有内置 Record 类型可用

2021-03-19 14:01 UTC, Nugine commented on src/auth/auth.decl.ts
> +//buya9o等级比较
这行是啥

2021-03-19 14:01 UTC, Nugine commented on src/auth/auth.decl.ts
> +    admin: 2,
admin 是指外部系统吗？如果是，建议修改命名。
我们的评测系统对外部系统提供服务，外部没有管理权限。

2021-03-19 14:01 UTC, Nugine commented on src/auth/auth.decl.ts
> +export const toRoleName = toRoleNameTemp;
这里既然使用了多个常量定义，建议修改命名法为 SHOUTY_SNAKE_CASE，例如 KEY_LENGTH。
成员变量一般用小驼峰命名，全局常量用全大写加下划线分隔。

2021-03-19 14:01 UTC, Nugine commented on src/auth/auth.guard.ts
> +                    req.ip
其实我觉得 IP 不是很重要，因为穿越多层转发时不一定会带上真实 IP，能保证拿到的 IP 只有部署机器上看到的远端 IP。

2021-03-19 14:01 UTC, Nugine commented on src/auth/dto/key.dto.ts
> +    @Length(keyLength,100, { message: lengthErrorMessage })
长度限制 100 是从密钥生成规则导出的吗？

2021-03-19 14:01 UTC, Nugine commented on src/auth/dto/roles.dto.ts
> +
<del>空文件建议删除，真要用的话再加。</del>

不知道为什么这条评论不能 resolve，就手动加一条删除线了

2021-03-19 14:01 UTC, Nugine commented on config/application.toml
> +rootSecretKey= "5ere56r7t89huytcrd6f789hugyctr678t9y657g8uhinuyt7fgugyftdr5rs64e57r68t79y80uyfd5e7r8yft"
部署时如何手动生成 root 密钥？

2021-03-19 14:01 UTC, Nugine commented on src/auth/auth.guard.ts
> +            .update(req.body ? JSON.stringify(req.body) : "")
JSON.stringify 一个对象时，得到的输出不能保证一致。签名方与校验方的计算结果可能不同。
应该用未经解析的 HTTP body 来计算哈希。

2021-03-19 14:01 UTC, Nugine commented on src/auth/key/key.controller.ts
> +export class KeyController {
@A0nameless0man  我们直接以这个 PR 合并时的密钥接口实现作为协议标准吧

2021-03-19 14:09 UTC, A0nameless0man commented on src/auth/auth.guard.ts
> +                    req.ip
我觉得作为log打一下还是有排查的意义。

2021-03-19 14:10 UTC, A0nameless0man commented on src/auth/key/key.controller.ts
> +export class KeyController {
好

2021-03-19 14:15 UTC, A0nameless0man commented on src/auth/key/key.controller.ts
> +export class KeyController {
那么在合并之前我需要调整评测机那边的算法确认可以对接。

2021-03-20 03:45 UTC, WanchengWildMan commented
昨天github一直上不去，，，然后今天就一起交了，大部分已经改了）

2021-03-20 03:49 UTC, WanchengWildMan commented
那么admin指的应该是谁的管理权限呢?外部系统没有管理权限，那指的是内部吗?

2021-03-22 04:11 UTC, WanchengWildMan commented
传输密钥时的加密措施是在哪里实现的啊）

2021-03-22 07:59 UTC, Nugine commented
> 那么admin指的应该是谁的管理权限呢?外部系统没有管理权限，那指的是内部吗?

根据 #11 的描述，只有 root 才能管理整个评测系统。外部系统和评测机都无权管理。

2021-03-22 12:36 UTC, Nugine commented
> 传输密钥时的加密措施是在哪里实现的啊）

是指生成密钥时的那个 HTTP 响应吗？可以用 root 密钥来加密。

2021-03-22 12:38 UTC, Nugine commented
#17 现在已经合并，用 git rebase 或 git merge 来解决冲突

2021-03-22 14:37 UTC, WanchengWildMan commented
key.service.ts
```typescript
    processKey(key: string) {
        return key
            .split("\n")
            .slice(1, 4)
            .join("")
            .replace("/", "A")
            .replace("+", "B")
            .substring(0, KEY_LENGTH_NOT_ROOT);
    }
    async generateKeyPair(roles: string[]): Promise<KeyPairDto> {
        let { publicKey, privateKey } = generateKeyPairSync("rsa", {
            modulusLength: KEY_LENGTH_NOT_ROOT * 16,
            publicKeyEncoding: {
                type: "spki",
                format: "pem"
            },
            privateKeyEncoding: {
                type: "pkcs8",
                format: "pem"
            }
        });
        publicKey = this.processKey(publicKey);
        privateKey = this.processKey(privateKey);
        //TODO 用root密钥对加密
        return {
            ak: publicKey,
            sk: privateKey,
            roles: roles
        };
    }
```
emm如果这里的ak和sk需要对数据加密解密而不仅仅是验证签名的话，，是否需要重构构造密钥的方法呢？

2021-03-22 14:53 UTC, Nugine commented
假设有个后台网页用来管理评测系统，那么这个后台网页能知道 root 的 AK 和 SK，评测系统也知道 root 的 AK 和 SK。
双方都知道密钥时，传输信息用某种对称加密即可。密钥生成方式不用改。

2021-04-09 14:03 UTC, Nugine requested changes
src/auth/node_modules 不应该包含在提交里，可以新加一个提交删掉。

2021-04-09 14:03 UTC, Nugine commented on src/auth/auth.decl.ts
> +const keyPoolsNamesArrTemp: string[] = [];
写个匿名函数就能去掉这些temp了

2021-04-09 14:03 UTC, Nugine commented on docs/认证模块.md
> +crypto库中的`generateKeyPairSync()`,带有PUBLICKEY/SECETKEY等字样的前缀或后缀，需截取中间部分1到4行，取中间`KEY_LENGTH_NOT_ROOT` 位。
这是个 typo 吗？
SECETKEY => SECRETKEY

2021-04-09 14:03 UTC, Nugine commented on docs/认证模块.md
> +       roles?: string[];
之前一个密钥对只能是一种角色，为什么改成了一对多，这里有什么特殊考虑吗

2021-04-28 09:17 UTC, WanchengWildMan commented
emm确认了）

2021-04-30 11:24 UTC, Nugine approved these changes, later dismissed

2021-04-30 11:53 UTC, Nugine approved these changes

2021-04-30 11:53 UTC, merged