Config processor 配置文件处理器 合并请求
ThinkSpiritLab/heng-controller pull request #2
Opened 2020-08-21 13:52 UTC by trionfordring

为当前项目添加一个简单的配置文件处理器，便于通过注解和ts对象之间访问配置文件数据。

2020-08-21 14:04 UTC, A0nameless0man requested changes
请恢复eslint并提供功能性测试

2020-08-21 14:04 UTC, A0nameless0man commented on src/config-processor/read-profile.ts
> +/* eslint-disable */
禁止关闭 eslint

2020-08-25 05:50 UTC, Nugine approved these changes
可以 squash and merge

@A0nameless0man 看看有没有问题

2020-08-25 12:32 UTC, A0nameless0man reviewed
我觉得OK,虽然硬编码字符串不是很好，但影响不大。实现的很漂亮。
@Nugine

2020-08-26 15:07 UTC, A0nameless0man approved these changes
可以有
实现的不错
同意合并

2020-08-26 15:11 UTC, merged

2021-02-09 14:55 UTC, Flaryer commented
有个bug，若配置文件内没有某个大属性，则不会检查类型。
如
```toml
# 正确配置
[scheduler]
xxx = 1
xxxx = 2

# 错误配置
......空



# 此时scheduler不会被检测，也没有报错
```

2021-02-10 04:14 UTC, Nugine commented
可以在 nested 那边都补上 `@IsNotEmpty()`

<https://github.com/typestack/class-validator#validation-decorators>